### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/model/2019430/streaming_mix_voice_12inst/e_100'

### ISSUE THREAD

**Issue by jjtail** [biboamy/instrument-streaming#2]
Dear biboamy
HI，I encountered some problems when I run `python3 prediction.py ocean.mp3`
`FileNotFoundError: [Errno 2] No such file or directory: '../data/model/2019430/streaming_mix_voice_12inst/e_100'`
How do I get this model file

**Comment by jjtail** [comment]
I also tried other inquiries under this folder, but the size is wrong 
```
size mismatch for decode.d_block4.conv1d.weight: copying a param with shape torch.Size([16, 10, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 12, 3, 3]).
	size mismatch for decode.d_block4.conv1d.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([12])
```

**Comment by biboamy** [comment]
Hello, thank you for pointing out. The code seems to be messed up during the last update. Now everything should work fine. Let me know if you have any questions.

**Comment by jjtail** [comment]
thank you  ~
