### ISSUE TITLE
Cannot parse the Musescore dataset

### ISSUE THREAD

**Issue by ta603** [biboamy/instrument-streaming#3]
Hello. Thank you for the great work.
When executing parse_url() in parse_data.py,
``` parsed_html.find_all('article', attrs={'role':'article'})``` gives nothing.
i.e.,

```python

>>>print(parsed_html.find_all('article', attrs={'role':'article'}))
[]

```
Would you tell me how to resolve this issue, please?

**Comment by biboamy** [comment]
Hello, thank you for your interest. It seems that the Musescore website has changed its website structure. I have updated the parser script and now it works again. Please let me know if you have further questions.

Note: For the new crawler, you have to set up the selenium environment on your computer.

**Comment by ta603** [comment]
Dear biboamy,
Thank you for the quick updates!
