### ISSUE TITLE
question about threshold 

### ISSUE THREAD

**Issue by Annabelle115** [biboamy/instrument-streaming#4]
hi ,How do you get the threshold to determine which instruments are dominant in a segment

**Comment by biboamy** [comment]
One way is to do manual tunning and get the threshold that produces the highest F1 score on the validation set. Another way is to automatically tune the threshold during training time. Here is the sample code: 
https://github.com/biboamy/instrument-prediction/blob/824d81f62e3c94ee1eb76d35d2cf52859c3ce125/function/evl.py#L42

**Comment by Annabelle115** [comment]
Thanks!You are so nice~
