### ISSUE TITLE
question about the dataset

### ISSUE THREAD

**Issue by Annabelle115** [biboamy/instrument-streaming#5]
sorry to bother you again ,but,could you show  some code for generating va_pitch.h5,tr_pitch.h5,va_stream.h5,tr_stream.h5?I am new to HDF5 T^T

**Comment by biboamy** [comment]
No problem. You can see a sample here: 
https://github.com/biboamy/instrument-streaming/blob/2e58eba7dbb4e28096cf4f27de4a7ebe972b5ba1/musicnet/preprocess.py#L49

Although this is not the original script to generate the va_pitch.h5, tr_stream.h5, etc... you can simply modify the file name to achieve the same data. Hope this helps.

**Comment by Akiiiira** [comment]
Hello. I'm interesting in your great study, and I have 2 question about to create musescore dataset.
According to the preprocess.py in musicnet, at first we loading the musicnet dataset by 
[data = np.load('./data/musicnet.npz', encoding='bytes').]
1st: About MuseScore, what is the variable corresponding to the data?
2nd: what will we do by parse_data.py? this create the dataset about MuseScore?
please tell me the procedure to create va_pitch.h5,tr_pitch.h5,va_stream.h5,tr_stream.h5.
